import { ILevel, IModule } from "@/entities/study";

export const mockLevels: ILevel[] = [
  {
    id: "lvl-1-1",
    title: "Введение",
    description: "Первые шаги",
    isCompleted: true,
    isCurrent: false,
    steps: [
      {
        id: "s-1",
        isCompleted: true,
        isCurrent: false,
        title: "Установка окружения",
        description:
          "Устанавливаем и настраиваем рабочее окружение для комфортной работы",
        type: "document",
        position: { x: 10, y: 60 },
      },
      {
        id: "s-2",
        isCompleted: true,
        isCurrent: false,
        title: "Переменные и типы",
        description:
          "Изучаем основу, на которой строится любой язык программирования",
        type: "code",
        position: { x: 60, y: 280 },
      },
      {
        id: "s-3",
        isCompleted: true,
        isCurrent: false,
        title: "Типы данных",
        description: "Важный аспект для понимания данных и как они разделяются",
        type: "quiz",
        position: { x: 20, y: 460 },
      },
      {
        id: "s-4",
        isCompleted: true,
        isCurrent: false,
        title: "Операторы",
        description: "Главные операции над данными",
        type: "exam",
        position: { x: 50, y: 740 },
      },
      {
        id: "s-4-1",
        isCompleted: true,
        isCurrent: false,
        title: "Условия и ветвления",
        description: "if / else, switch и тернарный оператор на практике",
        type: "code",
        position: { x: 15, y: 1020 },
      },
      {
        id: "s-4-2",
        isCompleted: true,
        isCurrent: false,
        title: "Практика: калькулятор",
        description: "Собираем мини-калькулятор на изученных конструкциях",
        type: "quiz",
        position: { x: 60, y: 1300 },
      },
    ],
  },
  {
    id: "lvl-1-2",
    title: "Функции",
    description: "Работа с функциями",
    isCompleted: true,
    isCurrent: false,
    steps: [
      {
        id: "s-5",
        isCompleted: true,
        isCurrent: false,
        title: "Объявление функций",
        description:
          "Объявляем обыкновенные функции и учимся вызывать. Какие бывают функции",
        type: "document",
        position: { x: 60, y: 60 },
      },
      {
        id: "s-6",
        isCompleted: true,
        isCurrent: false,
        title: "Стрелочные функции",
        description: "Особый вид функции, используемый в 90% случаев",
        type: "code",
        position: { x: 10, y: 240 },
      },
      {
        id: "s-7",
        isCompleted: true,
        isCurrent: false,
        title: "Замыкания",
        description: "Важное свойство функций",
        type: "exam",
        position: { x: 70, y: 480 },
      },
      {
        id: "s-7-1",
        isCompleted: true,
        isCurrent: false,
        title: "Параметры и аргументы",
        description: "Разбираем default-параметры, rest и spread-операторы",
        type: "document",
        position: { x: 10, y: 620 },
      },
      {
        id: "s-7-2",
        isCompleted: true,
        isCurrent: false,
        title: "Callback-функции",
        description: "Передаём функции как значения и вызываем их позже",
        type: "code",
        position: { x: 70, y: 850 },
      },
      {
        id: "s-7-3",
        isCompleted: true,
        isCurrent: false,
        title: "Тест по функциям",
        description: "Проверяем понимание области видимости и this",
        type: "quiz",
        position: { x: 20, y: 1180 },
      },
    ],
  },
  {
    id: "lvl-1-3",
    title: "Объекты",
    description: "Работа с объектами",
    isCompleted: true,
    isCurrent: false,
    steps: [
      {
        id: "s-8",
        isCompleted: true,
        isCurrent: false,
        title: "Создание объектов",
        description:
          "На этом строится 90% языка. Эти знания приблизят вас к истине!",
        type: "document",
        position: { x: 50, y: 60 },
      },
      {
        id: "s-9",
        isCompleted: true,
        isCurrent: false,
        title: "Методы объектов",
        description: "Научимся вертеть и крутить объектами так, как хотим мы",
        type: "code",
        position: { x: 70, y: 270 },
      },
      {
        id: "s-9-1",
        isCompleted: true,
        isCurrent: false,
        title: "Деструктуризация",
        description: "Достаём поля объектов в переменные кратко и элегантно",
        type: "code",
        position: { x: 10, y: 480 },
      },
      {
        id: "s-9-2",
        isCompleted: true,
        isCurrent: false,
        title: "Spread и rest в объектах",
        description: "Копируем, объединяем и переопределяем свойства",
        type: "document",
        position: { x: 60, y: 650 },
      },
      {
        id: "s-9-3",
        isCompleted: true,
        isCurrent: false,
        title: "Практика: профиль",
        description: "Собираем объект пользователя с вложенными полями",
        type: "quiz",
        position: { x: 10, y: 880 },
      },
    ],
  },
  {
    id: "lvl-1-4",
    title: "Массивы и коллекции",
    description: "Перебор, трансформация и поиск",
    isCompleted: false,
    isCurrent: true,
    steps: [
      {
        id: "s-10",
        isCompleted: true,
        isCurrent: false,
        title: "Основы массивов",
        description: "Создание, доступ по индексу, длина и базовые операции",
        type: "document",
        position: { x: 10, y: 60 },
      },
      {
        id: "s-11",
        isCompleted: true,
        isCurrent: false,
        title: "Методы push/pop/shift",
        description: "Добавляем и удаляем элементы с обоих концов массива",
        type: "code",
        position: { x: 40, y: 460 },
      },
      {
        id: "s-12",
        isCompleted: false,
        isCurrent: true,
        title: "map, filter, reduce",
        description: "Три кита функциональной работы с массивами",
        type: "code",
        position: { x: 80, y: 900 },
      },
      {
        id: "s-13",
        isCompleted: false,
        isCurrent: false,
        title: "Поиск элементов",
        description: "find, findIndex, includes и некоторые",
        type: "quiz",
        position: { x: 30, y: 1300 },
      },
      {
        id: "s-14",
        isCompleted: false,
        isCurrent: false,
        title: "Сортировка массивов",
        description: "sort с компаратором и стабильность сортировки",
        type: "exam",
        position: { x: 20, y: 1700 },
      },
      {
        id: "s-15",
        isCompleted: false,
        isCurrent: false,
        title: "Практика: корзина",
        description:
          "Считаем сумму, фильтруем товары и группируем по категориям",
        type: "quiz",
        position: { x: 50, y: 2100 },
      },
    ],
  },
  {
    id: "lvl-1-5",
    title: "Асинхронность",
    description: "Промисы, async/await и Event Loop",
    isCompleted: false,
    isCurrent: false,
    steps: [
      {
        id: "s-16",
        isCompleted: false,
        isCurrent: false,
        title: "Event Loop",
        description: "Как устроен цикл событий и почему это важно",
        type: "document",
        position: { x: 10, y: 60 },
      },
      {
        id: "s-17",
        isCompleted: false,
        isCurrent: false,
        title: "setTimeout и setInterval",
        description: "Отложенные и периодические вызовы функций",
        type: "code",
        position: { x: 90, y: 480 },
      },
      {
        id: "s-18",
        isCompleted: false,
        isCurrent: false,
        title: "Промисы",
        description: "then / catch / finally и цепочки промисов",
        type: "code",
        position: { x: 20, y: 940 },
      },
      {
        id: "s-19",
        isCompleted: false,
        isCurrent: false,
        title: "async / await",
        description: "Синтаксический сахар над промисами",
        type: "document",
        position: { x: 80, y: 1360 },
      },
      {
        id: "s-20",
        isCompleted: false,
        isCurrent: false,
        title: "Обработка ошибок",
        description: "try / catch и типичные ошибки асинхронного кода",
        type: "quiz",
        position: { x: 30, y: 1780 },
      },
      {
        id: "s-21",
        isCompleted: false,
        isCurrent: false,
        title: "Экзамен по модулю",
        description: "Итоговая проверка знаний по всему модулю",
        type: "exam",
        position: { x: 70, y: 2200 },
      },
    ],
  },
];

export const modules: IModule[] = [
  {
    id: "mod-1",
    title: "Основы JavaScript",
    description: "Базовый синтаксис и концепции",
    isCompleted: true,
    isCurrent: false,
    levels: mockLevels,
  },
  {
    id: "mod-2",
    title: "продвинутый JavaScript",
    description: "Продвинутые механизмы и синтаксис языка",
    isCompleted: false,
    isCurrent: true,
    levels: mockLevels,
  },
  {
    id: "mod-3",
    title: "Senior JavaScript",
    description: "JavaScript для Senior-специалистов и ваще самых крутых типов",
    isCompleted: false,
    isCurrent: false,
    levels: mockLevels,
  },
];
