import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/index.css";
import { UIThemeProvider, ThemeEnum, ThemeSwitcher } from "@/shared/ui/kit";
import { StoreProvider } from "./providers/store";
import { AuthProvider } from "./providers/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClassname = `${geistSans.variable} ${geistMono.variable} antialiased`;

  const availableThemes = [ThemeEnum.LIGHT, ThemeEnum.DARK];

  return (
    <html lang="en">
      <body className={bodyClassname}>
        <StoreProvider>
          <AuthProvider>
            <UIThemeProvider theme={ThemeEnum.LIGHT}>
              <ThemeSwitcher
                availableThemes={availableThemes}
                className="absolute z-90 right-2 top-2"
              />
              {children}
            </UIThemeProvider>
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
